### PR TITLE
Add weather

### LINKED ISSUE #6: add weather
We have 

    <current weather>

in the HTML but that won't work until HTML7 I think.

In the mean time, let's use this: http://simpleweatherjs.com/ (there is a `currently` and `text` field that could be what we want, and an example [here](http://codepen.io/fleeting/pen/xklfq)).

### PR DESCRIPTION
**Pull request by techieshark**
Adds text and icon for current weather:

image

Fixes #6

### CODE REVIEW

**Comment by maya** [comment]
This also looks great @techieshark. Maybe we should look at some of the most common SF weather options and make sure they are adjectives.
fog

**Comment by techieshark** [comment]
thanks @maya! do you want to have a go at that?

**Comment by davidrleonard** [comment]
Adds custom adjectives for weather so it always makes sense (dd85744 e555270 d4f71f8)

Removes simpleWeather plugin and calls Yahoo Weather API directly (3511781 ced3a9e)

Yo @techieshark feel free to revert the last two if it doesn't make sense. Since we already had the data, I just rewrote it to not rely on a plugin, but don't mind keeping the plugin if that makes more sense. :+1:

**Comment by jeremiak** [comment]
:heart: this whole thing

oh hai from the :ocean: :sunny: :palm_tree:

**Pull request merged**
