### PR TITLE
new logo and background

### LINKED ISSUE #4: New look and feel
Ainsley made us a sweet new pattern and design: Screenshot

Here's the logo file: http://up.jeremiak.com/Z38i
background pattern: http://up.jeremiak.com/Z2qL

There are some copy changes in #3 that we'll also want to incorporate.

### PR DESCRIPTION
**Pull request by techieshark**
This resolves #4.

I changed the type from black to white to match the logo, adjusted margins, etc. 

Todo before merge:

- [x] copy updates
- [x] logo
- [x] background
- [x] style updates
- [x] make responsive

### CODE REVIEW

**Comment by techieshark** [comment]
Also, it should look like this:

image

**Comment by davidrleonard** [comment]
I made it mobile responsive and removed the text-shadow. Thanks, @techieshark and @jeremiak.

**Comment by davidrleonard** [comment]
We need to actually have that inquire within call-to-action do something. Should we have an email inbox or a contact form?

**Comment by techieshark** [comment]
@davidrleonard these changes look good. Thanks!

Let's see if @drewrwilson or @maya can figure out the 'inquire w/in' bit.

**Comment by techieshark** [comment]
Discussed with @davidrleonard. Agreed to move call to action copy & functionality (email, form, etc) separate issue (#7). 

This should be ready for review/test/merge.

**Comment by jeremiak** [comment]
Looks good to me! I'm going to go ahead and merge

**Pull request merged**
